name: Build Desktop Apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      SOLUTION_PATH: Tournaments.sln
      BUILD_CONFIGURATION: Release
      BUILD_PLATFORM: Any CPU

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore solution
        run: msbuild $env:SOLUTION_PATH /t:Restore /p:Configuration="$env:BUILD_CONFIGURATION" /p:Platform="$env:BUILD_PLATFORM"

      - name: Build solution
        run: msbuild $env:SOLUTION_PATH /t:Build /p:Configuration="$env:BUILD_CONFIGURATION" /p:Platform="$env:BUILD_PLATFORM" /m

      - name: Upload WinForms artifact
        uses: actions/upload-artifact@v4
        with:
          name: tournaments-winforms-release
          path: |
            Tournaments/bin/Release/**
          if-no-files-found: error

      - name: Upload WPF artifact
        uses: actions/upload-artifact@v4
        with:
          name: tournaments-wpf-release
          path: |
            WPF/bin/Release/net48/**
          if-no-files-found: error
